DeviceSensorWeb/Models/Device.cs
using System;
using System.Collections;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace DeviceSensorWeb.Models
{
    public class Device
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [BsonRequired]
        [BsonRepresentation(BsonType.String)]
        public string SerialNumber { get; set; }

        [BsonRequired]
        [BsonRepresentation(BsonType.DateTime)]
        public DateTime RegistrationDate { get; set; }

        [BsonRequired]
        [BsonRepresentation(BsonType.String)]
        public string FirmwareVersion { get; set; }

#pragma warning disable CA2227 // Collection properties should be read only
        public IEnumerable<SensorReadings> SensorReadings { get; set; } = new List<SensorReadings>();
#pragma warning restore CA2227 // Collection properties should be read only
    }
}

DeviceSensorWeb/Models/DeviceDatabaseSettings.cs
namespace DeviceSensorWeb.Models
{
    public class DeviceDatabaseSettings : IDeviceDatabaseSettings
    {
        public string DeviceCollectionName { get; set; }
        public string ConnectionString { get; set; }
        public string DatabaseName { get; set; }
    }

    public interface IDeviceDatabaseSettings
    {
        string DeviceCollectionName { get; set; }
        string ConnectionString { get; set; }
        string DatabaseName { get; set; }
    }
}

DeviceSensorWeb/Models/DeviceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeviceSensorWeb.Models;

namespace DeviceSensorWeb.Models
{
    public class DeviceViewModel
    {
        Device Device { get; set; }
    }
}

DeviceSensorWeb/Models/DevicesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeviceSensorWeb.Models
{
    public class DevicesViewModel
    {
        public IEnumerable<Device> Devices { get; set; }
    }
}

DeviceSensorWeb/Models/ErrorViewModel.cs
using System;

namespace DeviceSensorWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DeviceSensorWeb/Models/SensorReading.cs
using System;
using System.ComponentModel.DataAnnotations;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace DeviceSensorWeb.Models
{
    public class SensorReadings
    {
        [DataType(DataType.DateTime)]
        [BsonRepresentation(BsonType.DateTime)]
        public DateTime ReadingDateTime { get; set; }

        [BsonRepresentation(BsonType.Double)]
        public double TemperatureCelcius { get; set; }

        [Range(0, 100)]
        [BsonRepresentation(BsonType.Double)]
        public double HumidityPercentage { get; set; }
        
        [Range(0, double.MaxValue)]
        [BsonRepresentation(BsonType.Double)]
        public double CarbonMonoxideLevel { get; set; }

        [BsonRepresentation(BsonType.String)]
        public string DeviceHealth { get; set; }
    }
}

DeviceSensorWeb/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeviceSensorWeb.Models
{
    public class User
    {
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        //public string FIRST_NAME { get; set; }
        //public string LAST_NAME { get; set; }
        //public string EMAILID { get; set; }
        //public string PHONE { get; set; }
        //public string ACCESS_LEVEL { get; set; }
        //public string READ_ONLY { get; set; }
    }
}

DeviceSensorWeb/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DeviceSensorWeb.CustomAttributes;
using DeviceSensorWeb.Services;
using DeviceSensorWeb.Models;

namespace DeviceSensorWeb.Controllers
{
    [Authorize]
    public class DeviceController : Controller
    {
        private DeviceService _deviceService;

        public DeviceController(DeviceService deviceService)
        {
            _deviceService = deviceService;
        }

        // GET: Device
        public ActionResult Index()
        {
            var devices = _deviceService.Get();

            var deviceVM = new DevicesViewModel()
            {
                Devices = devices
            };

            return View(deviceVM);
        }

        public ActionResult Details(string deviceId)
        {
            var device = _deviceService.Get(deviceId);

            return View(device);
        }

        [HttpGet("[controller]/GetDevices")]
        public ActionResult<List<Device>> GetDevices()
        {
            var devices = _deviceService.Get();

            return devices;
        }

        [HttpGet("[controller]/GetDevice")]
        public ActionResult<Device> GetDevice(string Id)
        {
            var device = _deviceService.Get(Id);

            return device;
        }

        // GET: Device/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: Device/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Device/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Device/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        // POST: Device/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Device/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Device/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

DeviceSensorWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DeviceSensorWeb.Models;
using Microsoft.AspNetCore.Http;

namespace DeviceSensorWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult LoginUser(User user)
        {
            TokenProvider _tokenProvider = new TokenProvider();
            //Authenticate user
            var userToken = _tokenProvider.LoginUser(user.USERID.Trim(), user.PASSWORD.Trim());
            if (userToken != null)
            {
                //Save token in session object
                HttpContext.Session.SetString("JWToken", userToken);
            }

            return Redirect("~/Home/Index");
        }
        public IActionResult Logoff()
        {
            HttpContext.Session.Clear();
            return Redirect("~/Home/Index");
        }
    }
}

DeviceSensorWeb/Views/Device/Details.cshtml
@model DeviceSensorWeb.Models.Device

@{
    ViewData["Title"] = "Details";
}

@section Scripts  {
<script type="text/javascript">
    window.deviceDetailsId = "@Model.Id";
</script>
}

<div id="deviceDetailsVue">

    @Html.ActionLink("Back to list", "Index", "Device")

    <h1>Device Details</h1>
    <p>Sensor details are updated every 15 seconds.</p>
    <p>Hover over the points on the graph to get time details. Graphs are set to display details scoped to a day.</p>
    <div class="field">
        <span class="field__label">Serial Number</span>
        <span class="field__value">@Model.SerialNumber</span>
    </div>
    <div class="field">
        <span class="field__label">Registered Date</span>
        <span class="field__value">{{formattedDate('@Model.RegistrationDate.ToUniversalTime().ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'")')}}</span>
    </div>
    <div class="field">
        <span class="field__label">Firmware Version</span>
        <span class="field__value">@Model.FirmwareVersion</span>
    </div>

    <div class="sensors">

        <div class="chart-div">
            <canvas ref="celciusChart" width="350" height="350"></canvas>
        </div>
        <div class="chart-div">
            <canvas ref="humidityChart" width="350" height="350"></canvas>
        </div>
        <div class="chart-div">
            <canvas ref="carbonMonoxideChart" width="350" height="350"></canvas>
        </div>

        @*@foreach (var sensorReading in Model.SensorReadings.OrderBy(sr => sr.ReadingDateTime))
        {
            <div class="field">
                <span class="field__label">Temperature in Celcius</span>
                <span class="field__value">@sensorReading.TemperatureCelcius</span>
            </div>
            <div class="field">
                <span class="field__label">Humidity Level Percentage</span>
                <span class="field__value">@sensorReading.HumidityPercentage</span>
            </div>
            <div class="field">
                <span class="field__label">Carbon Monoxide Level in PPM</span>
                <span class="field__value">@sensorReading.CarbonMonoxideLevel</span>
            </div>
        }*@

    </div>

    <button class="btn btn-primary" type="button" data-toggle="collapse" href="#sensorHealth" role="button" aria-expanded="false" aria-controls="sensorHealth">
        Sensor Health Details
    </button>

    <div class="collapse" id="sensorHealth">
        <div class="card card-body">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Date of Reading</th>
                        <th>Device Health</th>
                    </tr>
                </thead>
                <tbody>

                    <tr v-for="reading in device.sensorReadings">
                        <td>{{formattedDate(reading.readingDateTime)}}</td>
                        <td>{{reading.deviceHealth}}</td>
                    </tr>
                    @*@foreach (var sensorReading in Model.SensorReadings)
                    {
                        <tr>
                            <td>@sensorReading.ReadingDateTime</td>
                            <td>@sensorReading.DeviceHealth</td>
                        </tr>
                    }*@
                </tbody>
            </table>
        </div>
    </div>
</div>

DeviceSensorWeb/Views/Device/Index.cshtml
@using DeviceSensorWeb.Models

@model DeviceSensorWeb.Models.DevicesViewModel

@{
    ViewData["Title"] = "Index";
}

<div id="deviceVue">
    <div>
        <h1>Devices</h1>
        <p>Device details are updated every 5 seconds.</p>
        <p>Click a device's Serial Number for additional details.</p>
    </div>

    <div class="row">
        <div v-if="!devices || !devices.hasOwnProperty('length')">
            <table class="data-table data-table--device">
                <thead>
                    <tr>
                        <th>Serial Number</th>
                        <th>Registered</th>
                        <th>Firmware Version</th>
                        <th>Readings Count</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var device in Model.Devices)
                    {
                        <tr>
                            <td>@Html.ActionLink(device.SerialNumber.ToString(), "Details", "Device", new { deviceId = device.Id })</td>
                            <td>{{formattedDate('@device.RegistrationDate.ToUniversalTime().ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'")')}}</td>
                            <td>@device.FirmwareVersion</td>
                            <td>@device.SensorReadings.Count()</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div v-else>
            <table class="data-table data-table--device">
                <thead>
                    <tr>
                        <th>Serial Number</th>
                        <th>Registered</th>
                        <th>Firmware Version</th>
                        <th>Readings Count</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="device in devices">
                        <td><a :href="deviceIdUrl(device)">{{device.serialNumber}}</a></td>
                        <td>{{formattedDate(device.registrationDate)}}</td>
                        <td>{{device.firmwareVersion}}</td>
                        <td>{{device.sensorReadings.length}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

DeviceSensorWeb/Views/Home/Index.cshtml
@model DeviceSensorWeb.Models.User

@{
    ViewData["Title"] = "Home Page";
}

<div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="row">
            <p>You're logged in as <span class="user__name">@User.Identity.Name</span>! Additional pages are now available</p>
        </div>
        <div class="row">
            @Html.ActionLink("Devices Page", "Index", "Device", null, new { @class = "nav-link" })
        </div>
        <div class="row" style="padding-top:50px;">
            @Html.ActionLink("Log Off", "Logoff",
            "Home", null, new { @class = "btn btn-primary btn-lg rph-login-button" })
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4">
                <div>
                    @using (Html.BeginForm("LoginUser", "Home", FormMethod.Post, new { role = "form" }))
                    {
                        <div>
                            @Html.AntiForgeryToken()
                            <div>
                                @Html.LabelFor(m => m.USERID)
                                <br />
                            </div>
                            <div>
                                @Html.TextBoxFor(m => m.USERID,
                                new { @class = "form-control txtbox" })
                            </div>
                            <div style="padding-top:20px;"></div>
                            <div>
                                @Html.LabelFor(m => m.PASSWORD)
                                <br />
                            </div>
                            <div>
                                @Html.PasswordFor(m => m.PASSWORD,
                                new { @class = "form-control txtbox" })
                            </div>
                        </div>
                        <div style="padding-left:35%;width:40%;">
                            <div style="padding-top:20px;">
                                <input class="btn btn-primary btn-lg rph-login-button" type="submit" value="Login" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</div>

DeviceSensorWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeviceSensorWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true" />
</head>
<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeviceSensorWeb</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Device" asp-action="Index">Devices</a>
                                </li>
                            }

                            @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>*@
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - DeviceSensorWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    @RenderSection("Scripts", required: false)
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://momentjs.com/downloads/moment.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="~/js/packages.min.js"></script>
    <script src="~/js/services.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</body>
</html>